import React, { useState, useRef } from 'react';
import { useApp } from '../contexts/AppContext';
import { format } from 'date-fns';
import {
  FileText,
  Printer,
  Download,
  Calendar,
  Activity,
  Pill,
  Users,
  Bell,
  TrendingUp
} from 'lucide-react';

const Reports = () => {
  const { t, generateReportData, playSound, isKidsMode } = useApp();
  const [selectedPeriod, setSelectedPeriod] = useState('today');
  const [reportData, setReportData] = useState(null);
  const reportRef = useRef(null);

  const periods = [
    { id: 'today', label: t('today') },
    { id: 'week', label: t('thisWeek') },
    { id: 'month', label: t('thisMonth') },
  ];

  const handleGenerateReport = () => {
    playSound('success');
    const data = generateReportData(selectedPeriod);
    setReportData(data);
  };

  const handlePrint = () => {
    playSound('click');
    window.print();
  };

  const handleDownload = () => {
    playSound('click');
    if (!reportData) return;

    // Generate text report
    let reportText = `ECHO Patient Communication Report\n`;
    reportText += `${'='.repeat(50)}\n\n`;
    reportText += `Report Period: ${format(reportData.startDate, 'MMM d, yyyy')} - ${format(reportData.endDate, 'MMM d, yyyy h:mm a')}\n\n`;

    reportText += `PAIN HISTORY\n${'-'.repeat(30)}\n`;
    if (reportData.painHistory.length === 0) {
      reportText += `No pain records in this period.\n`;
    } else {
      reportData.painHistory.forEach(p => {
        reportText += `- Level ${p.level}/10 at ${format(new Date(p.timestamp), 'MMM d, h:mm a')}`;
        if (p.bodyParts?.length > 0) {
          reportText += ` (${p.bodyParts.join(', ')})`;
        }
        reportText += `\n`;
      });
    }

    reportText += `\nMEDICATION HISTORY\n${'-'.repeat(30)}\n`;
    if (reportData.medicationHistory.length === 0) {
      reportText += `No medications taken in this period.\n`;
    } else {
      reportData.medicationHistory.forEach(m => {
        reportText += `- ${m.name} (${m.dosage}) taken at ${format(new Date(m.takenAt), 'MMM d, h:mm a')}\n`;
      });
    }

    reportText += `\nVISITOR HISTORY\n${'-'.repeat(30)}\n`;
    if (reportData.visitorHistory.length === 0) {
      reportText += `No visitors in this period.\n`;
    } else {
      reportData.visitorHistory.forEach(v => {
        reportText += `- ${v.name} (${v.relationship}): ${format(new Date(v.checkInTime), 'h:mm a')} - ${format(new Date(v.checkOutTime), 'h:mm a')}\n`;
      });
    }

    reportText += `\nCOMMUNICATION LOG\n${'-'.repeat(30)}\n`;
    if (reportData.communicationLog.length === 0) {
      reportText += `No communications in this period.\n`;
    } else {
      reportData.communicationLog.forEach(c => {
        reportText += `- [${format(new Date(c.timestamp), 'h:mm a')}] ${c.message}\n`;
      });
    }

    reportText += `\n${'='.repeat(50)}\n`;
    reportText += `Generated by ECHO Patient Communication App\n`;
    reportText += `Generated at: ${format(new Date(), 'MMM d, yyyy h:mm a')}\n`;

    // Download as text file
    const blob = new Blob([reportText], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `echo-report-${selectedPeriod}-${format(new Date(), 'yyyy-MM-dd')}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const avgPain = reportData?.painHistory.length > 0
    ? Math.round(reportData.painHistory.reduce((sum, p) => sum + p.level, 0) / reportData.painHistory.length)
    : 0;

  return (
    <div className="p-4">
      <h2 className={`text-2xl font-bold mb-6 text-center ${isKidsMode ? 'text-yellow-400' : 'gradient-text'}`}>
        {t('reports')}
      </h2>

      {/* Period selection */}
      <div className="glass rounded-2xl p-4 mb-6">
        <h3 className="text-lg font-semibold text-gray-300 mb-3 flex items-center gap-2">
          <Calendar className="w-5 h-5" />
          {t('reportPeriod')}
        </h3>

        <div className="flex gap-2 mb-4">
          {periods.map((period) => (
            <button
              key={period.id}
              onClick={() => { setSelectedPeriod(period.id); playSound('click'); }}
              className={`flex-1 py-2 px-3 rounded-xl font-semibold transition-all ${
                selectedPeriod === period.id
                  ? 'bg-gradient-to-r from-purple-500 to-pink-500 text-white'
                  : 'bg-dark-700 text-gray-400 hover:bg-dark-600'
              }`}
            >
              {period.label}
            </button>
          ))}
        </div>

        <button
          onClick={handleGenerateReport}
          className={`w-full py-3 rounded-xl font-bold transition-all btn-glow ${
            isKidsMode
              ? 'bg-gradient-to-r from-yellow-500 to-orange-500 hover:from-yellow-400 hover:to-orange-400'
              : 'bg-gradient-to-r from-purple-500 to-pink-500 hover:from-purple-400 hover:to-pink-400'
          } text-white flex items-center justify-center gap-2`}
        >
          <FileText className="w-5 h-5" />
          {t('generateReport')}
        </button>
      </div>

      {/* Generated report */}
      {reportData && (
        <div ref={reportRef} className="space-y-4">
          {/* Report header */}
          <div className="glass rounded-2xl p-6 print:bg-white print:text-black">
            <div className="flex items-center justify-between mb-4">
              <div>
                <h3 className="text-2xl font-bold text-white print:text-black">
                  ECHO Patient Report
                </h3>
                <p className="text-gray-400 print:text-gray-600">
                  {format(reportData.startDate, 'MMM d, yyyy')} - {format(reportData.endDate, 'MMM d, yyyy')}
                </p>
              </div>
              <div className="flex gap-2 no-print">
                <button
                  onClick={handlePrint}
                  className="p-3 bg-dark-600 hover:bg-dark-500 rounded-xl transition-all"
                >
                  <Printer className="w-5 h-5 text-gray-300" />
                </button>
                <button
                  onClick={handleDownload}
                  className="p-3 bg-dark-600 hover:bg-dark-500 rounded-xl transition-all"
                >
                  <Download className="w-5 h-5 text-gray-300" />
                </button>
              </div>
            </div>

            {/* Summary stats */}
            <div className="grid grid-cols-2 md:grid-cols-4 gap-4 mb-6">
              <div className="bg-dark-700 print:bg-gray-100 rounded-xl p-4 text-center">
                <Activity className="w-6 h-6 mx-auto text-orange-400 mb-2" />
                <p className="text-2xl font-bold text-white print:text-black">{avgPain}</p>
                <p className="text-sm text-gray-400 print:text-gray-600">Avg Pain</p>
              </div>
              <div className="bg-dark-700 print:bg-gray-100 rounded-xl p-4 text-center">
                <Pill className="w-6 h-6 mx-auto text-purple-400 mb-2" />
                <p className="text-2xl font-bold text-white print:text-black">{reportData.medicationHistory.length}</p>
                <p className="text-sm text-gray-400 print:text-gray-600">Meds Taken</p>
              </div>
              <div className="bg-dark-700 print:bg-gray-100 rounded-xl p-4 text-center">
                <Users className="w-6 h-6 mx-auto text-cyan-400 mb-2" />
                <p className="text-2xl font-bold text-white print:text-black">{reportData.visitorHistory.length}</p>
                <p className="text-sm text-gray-400 print:text-gray-600">Visitors</p>
              </div>
              <div className="bg-dark-700 print:bg-gray-100 rounded-xl p-4 text-center">
                <Bell className="w-6 h-6 mx-auto text-pink-400 mb-2" />
                <p className="text-2xl font-bold text-white print:text-black">{reportData.alerts.length}</p>
                <p className="text-sm text-gray-400 print:text-gray-600">Alerts</p>
              </div>
            </div>
          </div>

          {/* Pain history section */}
          <div className="glass rounded-2xl p-4 print:bg-white print:border print:border-gray-300">
            <h4 className="font-semibold text-gray-300 print:text-black mb-4 flex items-center gap-2">
              <TrendingUp className="w-5 h-5" />
              Pain History ({reportData.painHistory.length} records)
            </h4>

            {reportData.painHistory.length === 0 ? (
              <p className="text-gray-500 text-center py-4">No pain records in this period</p>
            ) : (
              <div className="space-y-2 max-h-48 overflow-y-auto print:max-h-none print:overflow-visible">
                {reportData.painHistory.map((entry, idx) => (
                  <div key={idx} className="flex items-center justify-between p-3 bg-dark-700 print:bg-gray-100 rounded-lg">
                    <div className="flex items-center gap-3">
                      <div className={`w-8 h-8 rounded-full flex items-center justify-center text-white font-bold
                        ${entry.level <= 3 ? 'bg-green-500' : entry.level <= 6 ? 'bg-yellow-500' : 'bg-red-500'}`}>
                        {entry.level}
                      </div>
                      <div>
                        <span className="text-gray-300 print:text-black font-medium">
                          Level {entry.level}/10
                        </span>
                        {entry.bodyParts?.length > 0 && (
                          <p className="text-xs text-gray-500">{entry.bodyParts.join(', ')}</p>
                        )}
                      </div>
                    </div>
                    <span className="text-sm text-gray-500">
                      {format(new Date(entry.timestamp), 'MMM d, h:mm a')}
                    </span>
                  </div>
                ))}
              </div>
            )}
          </div>

          {/* Medication history section */}
          <div className="glass rounded-2xl p-4 print:bg-white print:border print:border-gray-300">
            <h4 className="font-semibold text-gray-300 print:text-black mb-4 flex items-center gap-2">
              <Pill className="w-5 h-5" />
              Medication History ({reportData.medicationHistory.length} records)
            </h4>

            {reportData.medicationHistory.length === 0 ? (
              <p className="text-gray-500 text-center py-4">No medications taken in this period</p>
            ) : (
              <div className="space-y-2 max-h-48 overflow-y-auto print:max-h-none print:overflow-visible">
                {reportData.medicationHistory.map((entry, idx) => (
                  <div key={idx} className="flex items-center justify-between p-3 bg-dark-700 print:bg-gray-100 rounded-lg">
                    <div>
                      <span className="text-white print:text-black font-medium">{entry.name}</span>
                      <span className="text-gray-400 print:text-gray-600 ml-2">{entry.dosage}</span>
                    </div>
                    <span className="text-sm text-gray-500">
                      {format(new Date(entry.takenAt), 'MMM d, h:mm a')}
                    </span>
                  </div>
                ))}
              </div>
            )}
          </div>

          {/* Communication log section */}
          <div className="glass rounded-2xl p-4 print:bg-white print:border print:border-gray-300">
            <h4 className="font-semibold text-gray-300 print:text-black mb-4 flex items-center gap-2">
              <Bell className="w-5 h-5" />
              Communication Log ({reportData.communicationLog.length} entries)
            </h4>

            {reportData.communicationLog.length === 0 ? (
              <p className="text-gray-500 text-center py-4">No communications in this period</p>
            ) : (
              <div className="space-y-2 max-h-48 overflow-y-auto print:max-h-none print:overflow-visible">
                {reportData.communicationLog.map((entry, idx) => (
                  <div key={idx} className="flex items-center justify-between p-3 bg-dark-700 print:bg-gray-100 rounded-lg">
                    <span className="text-gray-300 print:text-black">{entry.message}</span>
                    <span className="text-sm text-gray-500 whitespace-nowrap ml-4">
                      {format(new Date(entry.timestamp), 'h:mm a')}
                    </span>
                  </div>
                ))}
              </div>
            )}
          </div>

          {/* Report footer */}
          <div className="text-center text-gray-500 text-sm py-4 print:text-black">
            <p>Generated by ECHO Patient Communication App</p>
            <p>Report generated at: {format(new Date(), 'MMMM d, yyyy h:mm a')}</p>
          </div>
        </div>
      )}
    </div>
  );
};

export default Reports;
